# Queries para o E-commerce

# Listar todos os produtos
query ListProducts @auth(level: PUBLIC) {
  products {
    id
    name
    price
    imageUrl
    category {
      name
    }
  }
}

# Obter um produto por ID
query GetProductById($id: UUID!) @auth(level: PUBLIC) {
  product(id: $id) {
    id
    name
    description
    price
    stockQuantity
    imageUrl
    category {
      name
    }
    productVariations_on_product {
      id
      name
      value
      additionalPrice
    }
    productImages_on_product {
      imageUrl
      isMain
    }
  }
}
